### ISSUE TITLE
Please check updating of chart within 100 miliseconds 

### ISSUE THREAD

**Issue by PawelSzymanski89** [kasvith/javafxrealtimecharts#2]
something's wrong :)

![obraz](https://user-images.githubusercontent.com/26041449/70374648-04837680-18f5-11ea-8ecf-f46ebce94efc.png)

look at points of data

**Comment by kasvith** [comment]
is this the normal setup or you changed something?

**Comment by kasvith** [comment]
100ms means we will have lot of data, you will have to remove multiple points i guess

**Comment by kasvith** [comment]
@PawelSzymanski89 We set the label for the chart in [here](https://github.com/kasvith/javafxrealtimechartsdemo/blob/853f091ed15780ebce91a16e3d644a7a7b0594d9/src/main/java/App.java#L57)

As you can see its `HH:mm:ss`, when you go 100ms this labelling scheme just doesn't work. You will have an extra 9 data points. That's why it's overlapping.

Change the label unit to this 

We are also considering the milliseconds now
```
// this is used to display time in HH:mm:ss:SS format
    final SimpleDateFormat simpleDateFormat =
        new SimpleDateFormat("HH:mm:ss:SS");
```

**Comment by PawelSzymanski89** [comment]
Ahh :) my bad thank you for exponation!
